// <auto-generated />
using System;
using FitnessDL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessDL.Migrations
{
    [DbContext(typeof(FitnessContext))]
    partial class FitnessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessDL.Models.CyclingSessionEF", b =>
                {
                    b.Property<int>("CyclingSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CyclingSessionID"));

                    b.Property<int>("AvgCadence")
                        .HasColumnType("int");

                    b.Property<int>("AvgWatt")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("MaxCadence")
                        .HasColumnType("int");

                    b.Property<int>("MaxWatt")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CyclingSessionID");

                    b.HasIndex("MemberID");

                    b.ToTable("CyclingSession");
                });

            modelBuilder.Entity("FitnessDL.Models.EquipmentEF", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InRepair")
                        .HasColumnType("bit");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FitnessDL.Models.MemberEF", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("FitnessDL.Models.ProgrammaEF", b =>
                {
                    b.Property<string>("ProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramCode");

                    b.ToTable("Programma");
                });

            modelBuilder.Entity("FitnessDL.Models.ReservationEF", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("TimeSlotID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FitnessDL.Models.RunningSession_DetailEF", b =>
                {
                    b.Property<int>("RunningSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunningSessionID"));

                    b.Property<float>("IntervalSpeed")
                        .HasColumnType("real");

                    b.Property<int>("IntervalTime")
                        .HasColumnType("int");

                    b.Property<int>("RunningSession_MainRunningSessionID")
                        .HasColumnType("int");

                    b.Property<int>("SeqNr")
                        .HasColumnType("int");

                    b.HasKey("RunningSessionID");

                    b.HasIndex("RunningSession_MainRunningSessionID");

                    b.ToTable("Runningsession_Detail");
                });

            modelBuilder.Entity("FitnessDL.Models.RunningSession_MainEF", b =>
                {
                    b.Property<int>("RunningSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunningSessionID"));

                    b.Property<float>("AvgSpeed")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("RunningSessionID");

                    b.HasIndex("MemberId");

                    b.ToTable("Runningsession_Main");
                });

            modelBuilder.Entity("FitnessDL.Models.Time_SlotEF", b =>
                {
                    b.Property<int>("TimeSlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSlotID"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("PartOfDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TimeSlotID");

                    b.ToTable("Time_Slot");
                });

            modelBuilder.Entity("MemberEFProgrammaEF", b =>
                {
                    b.Property<int>("MembersMemberID")
                        .HasColumnType("int");

                    b.Property<string>("ProgrammasProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MembersMemberID", "ProgrammasProgramCode");

                    b.HasIndex("ProgrammasProgramCode");

                    b.ToTable("MemberEFProgrammaEF");
                });

            modelBuilder.Entity("FitnessDL.Models.CyclingSessionEF", b =>
                {
                    b.HasOne("FitnessDL.Models.MemberEF", "Member")
                        .WithMany("CyclingSessions")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessDL.Models.ReservationEF", b =>
                {
                    b.HasOne("FitnessDL.Models.EquipmentEF", "Equipment")
                        .WithMany("Reservations")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessDL.Models.MemberEF", "Member")
                        .WithMany("Reservations")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessDL.Models.Time_SlotEF", "TimeSlot")
                        .WithMany("Reservations")
                        .HasForeignKey("TimeSlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Member");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("FitnessDL.Models.RunningSession_DetailEF", b =>
                {
                    b.HasOne("FitnessDL.Models.RunningSession_MainEF", "RunningSession_Main")
                        .WithMany("RunningSession_Details")
                        .HasForeignKey("RunningSession_MainRunningSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunningSession_Main");
                });

            modelBuilder.Entity("FitnessDL.Models.RunningSession_MainEF", b =>
                {
                    b.HasOne("FitnessDL.Models.MemberEF", "Member")
                        .WithMany("Sessions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MemberEFProgrammaEF", b =>
                {
                    b.HasOne("FitnessDL.Models.MemberEF", null)
                        .WithMany()
                        .HasForeignKey("MembersMemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessDL.Models.ProgrammaEF", null)
                        .WithMany()
                        .HasForeignKey("ProgrammasProgramCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessDL.Models.EquipmentEF", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("FitnessDL.Models.MemberEF", b =>
                {
                    b.Navigation("CyclingSessions");

                    b.Navigation("Reservations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FitnessDL.Models.RunningSession_MainEF", b =>
                {
                    b.Navigation("RunningSession_Details");
                });

            modelBuilder.Entity("FitnessDL.Models.Time_SlotEF", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
