// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StripsDL;

#nullable disable

namespace StripsDL.Migrations
{
    [DbContext(typeof(StripsContext))]
    [Migration("20241219214333_Strips")]
    partial class Strips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuteurEFStripEF", b =>
                {
                    b.Property<int>("AuteursAuteurID")
                        .HasColumnType("int");

                    b.Property<int>("StripsStripID")
                        .HasColumnType("int");

                    b.HasKey("AuteursAuteurID", "StripsStripID");

                    b.HasIndex("StripsStripID");

                    b.ToTable("AuteurEFStripEF");
                });

            modelBuilder.Entity("StripsDL.Models.AuteurEF", b =>
                {
                    b.Property<int>("AuteurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuteurID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuteurID");

                    b.ToTable("Auteur");
                });

            modelBuilder.Entity("StripsDL.Models.ReeksEF", b =>
                {
                    b.Property<int>("ReeksID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReeksID"));

                    b.Property<string>("ReeksNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReeksID");

                    b.ToTable("Reeks");
                });

            modelBuilder.Entity("StripsDL.Models.StripEF", b =>
                {
                    b.Property<int>("StripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StripID"));

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<int>("ReeksID")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UitgeverijID")
                        .HasColumnType("int");

                    b.HasKey("StripID");

                    b.HasIndex("ReeksID");

                    b.HasIndex("UitgeverijID");

                    b.ToTable("Strip");
                });

            modelBuilder.Entity("StripsDL.Models.UitgeverijEF", b =>
                {
                    b.Property<int>("UitgeverijID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UitgeverijID"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UitgeverijID");

                    b.ToTable("Uitgeverij");
                });

            modelBuilder.Entity("AuteurEFStripEF", b =>
                {
                    b.HasOne("StripsDL.Models.AuteurEF", null)
                        .WithMany()
                        .HasForeignKey("AuteursAuteurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StripsDL.Models.StripEF", null)
                        .WithMany()
                        .HasForeignKey("StripsStripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StripsDL.Models.StripEF", b =>
                {
                    b.HasOne("StripsDL.Models.ReeksEF", "Reeks")
                        .WithMany("Strips")
                        .HasForeignKey("ReeksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StripsDL.Models.UitgeverijEF", "Uitgeverij")
                        .WithMany("Strips")
                        .HasForeignKey("UitgeverijID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reeks");

                    b.Navigation("Uitgeverij");
                });

            modelBuilder.Entity("StripsDL.Models.ReeksEF", b =>
                {
                    b.Navigation("Strips");
                });

            modelBuilder.Entity("StripsDL.Models.UitgeverijEF", b =>
                {
                    b.Navigation("Strips");
                });
#pragma warning restore 612, 618
        }
    }
}
